import subprocess
import sys
import os
import pytest

# === TEST GENERATED BY AI (GitHub Copilot) ===
# Please manually review this test for correctness and completeness.

def test_sum_numbers_cli_basic(tmp_path):
    """
    Test the CLI with basic input.
    """
    script = os.path.join(
        os.path.dirname(__file__),
        "../src/sum_numbers.py"
    )
    script = os.path.abspath(script)
    result = subprocess.run(
        [sys.executable, script, "1", "2", "3"],
        capture_output=True,
        text=True
    )
    assert result.returncode == 0
    assert "Sum of [1.0, 2.0, 3.0] is 6.0" in result.stdout

def test_sum_numbers_cli_negative(tmp_path):
    """
    Test the CLI with negative numbers.
    """
    script = os.path.join(
        os.path.dirname(__file__),
        "../src/sum_numbers.py"
    )
    script = os.path.abspath(script)
    result = subprocess.run(
        [sys.executable, script, "-1", "2"],
        capture_output=True,
        text=True
    )
    assert result.returncode == 0
    assert "Sum of [-1.0, 2.0] is 1.0" in result.stdout
